apiVersion: 1

datasources:
  # Prometheus for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://mvcweb-prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    editable: true

  # Jaeger for traces
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://mvcweb-jaeger:16686
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: 'prometheus'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        queries:
          - name: 'Request rate'
            query: |
              sum(rate(piranha_pages_views[$__rate_interval])) by (page_id)
          - name: 'Workflow transitions'
            query: |
              sum(rate(piranha_workflow_transitions[$__rate_interval])) by (content_type, state)
    editable: true

  # Loki for logs (optional, if you want to add log aggregation)
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    editable: true