apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://mvcweb-prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  # Jaeger datasource for traces
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://mvcweb-jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags: ['job', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: true
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: true
        filterBySpanID: false