global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape MvcWeb application metrics
  - job_name: 'mvcweb'
    static_configs:
      - targets: ['mvcweb-app:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scrape Prometheus own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Jaeger v2 internal metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['mvcweb-jaeger:8888']
    scrape_interval: 10s

  # Scrape span metrics from Jaeger v2
  - job_name: 'jaeger-spanmetrics'
    static_configs:
      - targets: ['mvcweb-jaeger:8889']
    scrape_interval: 10s
  
  # Scrape metrics from OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['mvcweb-otel-collector:8889']
    scrape_interval: 10s
    metrics_path: '/metrics'