global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape MvcWeb application metrics
  - job_name: 'mvcweb'
    static_configs:
      - targets: ['mvcweb-app:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['mvcweb-otel-collector:8888']
    scrape_interval: 10s

  # Scrape Prometheus own metrics
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']